[project]
name = "justshare"
version = "1.0.0"
description = "A serious game to raise awareness about grooming, which uses different NLP techniques to simulate free choice."
requires-python = ">=3.12"
dependencies = [
    "es-core-news-sm",
    "fastapi[standard]>=0.128.0",
    "gensim>=4.4.0",
    "loguru>=0.7.3",
    "nltk>=3.9.2",
    "numpy>=2.4.1",
    "pydantic-settings>=2.12.0",
    "spacy>=3.8.11",
    "uvicorn[standard]>=0.40.0",
    "torch>=2.9.1",
    "transformers>=4.57.6",
    "keras>=3.13.2",
    "tensorflow>=2.21.0",
    "faiss-cpu>=1.13.2",
    "scikit-learn>=1.8.0",
    "spylls>=0.1.7",
]

[dependency-groups]
dev = [
    "tqdm>=4.67.3",
    "langchain-ollama>=1.1.0",
    "hf-xet>=1.2.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "pip>=26.0",
    "pandas>=3.0.1",
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
    "pyi18next>=0.0.2",
]

[tool.uv.sources]
es-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl" }
torch = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
