[project]
name = "justshare"
version = "1.0.0"
description = "A serious game to raise awareness about grooming, which uses different NLP techniques to simulate free choice."
requires-python = ">=3.12"
dependencies = [
    "autocorrect>=2.6.1",
    "cachetools>=6.2.4",
    "fastapi[standard]>=0.128.0",
    "gensim>=4.4.0",
    "langchain-ollama>=1.0.1",
    "loguru>=0.7.3",
    "nltk>=3.9.2",
    "numpy>=2.4.1",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
